wandb_version: 1

dataset:
  desc: null
  value: bracs
pretrain:
  desc: null
  value: natural_supervised
arch:
  desc: null
  value: ga
num_tokens:
  desc: null
  value: 5
num_masked_instances:
  desc: null
  value: 10
mask_drop:
  desc: null
  value: 0.6
lr:
  desc: null
  value: 0.0001
seed:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.10.15
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.34.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1728698162.781712
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.10.15
      5: 0.15.8
      6: 4.34.1
      8:
      - 5
